CREATE TABLE movie
(
  titleandyear character varying(200) NOT NULL,
  imdbid character varying(100),
  imdbvotes bigint,
  imdbavgrating real,
  imdbtitle character varying(200),
  imdbyear character varying(100),
  imdbdistribution character varying(20),
  omdbrated character varying(100),
  omdbreleased character varying(100),
  omdbruntime character varying(100),
  omdbgenre character varying(1000),
  omdbdirector character varying(1000),
  omdbwriter character varying(1000),
  omdbactors character varying(2000),
  omdbplot character varying(2000),
  omdblanguage character varying(200),
  omdbcountry character varying(200),
  omdbawards character varying(2000),
  omdbposter character varying(200),
  omdbmetascore character varying(100),
  omdbtype character varying(100),
  omdbdvd character varying(200),
  omdbboxoffice character varying(200),
  omdbproduction character varying(1000),
  omdbwebsite character varying(200),
  tomatometer character varying(100),
  tomatoimage character varying(100),
  tomatorating character varying(100),
  tomatoreviews character varying(100),
  tomatofresh character varying(100),
  tomatorotten character varying(100),
  tomatoconsensus character varying(1000),
  tomatousermeter character varying(100),
  tomatouserrating character varying(100),
  tomatouserreviews character varying(1000),
  tomatourl character varying(200),
  CONSTRAINT movie_pkey PRIMARY KEY (titleandyear)
)
